---
#master_ip: 172.28.128.13
http_port: 443
ip_addr_apache1: 192.168.56.117
ip_addr_apache2: 192.168.56.118
cert_name: ansible.com.crt
key_name: ansible.com.pem
csr_name: ansible.com.csr
path_to_cert: /home/vagrant/ssl
path_to_key: /home/vagrant/ssl
path_to_csr: /home/vagrant/ssl
master_ip: 192.168.56.119
slave_ip: 192.168.56.120
backend1_ip: 192.168.56.117
backend2_ip: 192.168.56.118
server_id_master: 1
server_id_slave: 2
hostname_master: db1-prod
hostname_slave: db2-prod
DB_replication: wordpress
wordpress_user: wordpress
wordpress_pass: password
db_user: root
db_password: password
mysql_root: root
mysql_slave: password
ENVIRONMENT: PRODUCTION
n: 5 
