---
- name: playbook
  hosts: all
  become: yes
  tasks:
  - name: Add the user 'ansible'
    user:
      name: ansible
      system: yes
  - name: .ssh
    file:
      path:  /home/ansible/.ssh
      state: directory
      owner: ansible
      group: ansible
      mode: 0700
   
   
