---
- name: Install mysql server
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - mysql-server
    - python-mysqldb
    - mysql-client 
  tags:
    - install

- name: Change rights /etc/environment 0666
  file: 
    path: /etc/environment
    mode: 0666

- name: Add ENVIRONMENT {{ ENVIRONMENT }} variable
  lineinfile:
    path: /etc/environment
    line: "ENVIRONMENT={{ ENVIRONMENT }}"

- name: Change rights /etc/environment 0644
  file: 
    path: /etc/environment
    mode: 0644

- name: Change root user password on first run
  mysql_user: login_user=root
              login_password={{ mysql_root }}
              check_implicit_admin=yes
              name=root
              password={{ mysql_root }}
              priv=*.*:ALL,GRANT
              host={{ item }}
  with_items:
    - "{{ master_ip }}"
    - "{{ slave_ip }}"
    - "{{ backend1_ip }}"
    - "{{ backend2_ip }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Add slave user
  mysql_user: login_user=root
              login_password={{ mysql_root }}
              check_implicit_admin=yes
              name=slave
              password={{ mysql_slave }}
              priv=*.*:ALL,GRANT
              host={{ item }}
  with_items:
    - "{{ master_ip }}"
    - "{{ slave_ip }}"
    - "{{ backend1_ip }}"
    - "{{ backend2_ip }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Add {{ wordpress_user }} user
  mysql_user: login_user=root
              login_password={{ mysql_root }}
              check_implicit_admin=yes
              name={{ wordpress_user }}
              password={{ wordpress_pass }}
              priv={{ DB_replication }}.*:ALL,GRANT
              host={{ item }}
  with_items:
    - "{{ backend1_ip }}"
    - "{{ backend2_ip }}"
    - 127.0.0.1
    - 172.28.128.5
    - localhost

- name: Add user
  when: n > 0
  mysql_user: login_user=root
              login_password={{ mysql_root }}
              check_implicit_admin=yes
              name="ecommerce-{{item}}"
              password="pa$$wd{{item}}"
              priv=*.*:ALL,GRANT
              host=localhost
  with_sequence: count={{n}}

- name: remove the MySQL test database
  action: mysql_db login_user=root login_password={{ mysql_root }} db=test state=absent
  tags:
    - removedb

- name: Create db {{ DB_replication }}
  mysql_db:
    name: "{{ DB_replication }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root }}"
  tags:
    - instdb
