---
- name: install nginx 
  apt: name=nginx state=latest update_cache=yes
  tags:
    - install

- name: Change rights /etc/environment 0666
  file:
    path: /etc/environment
    mode: 0666

- name: Add ENVIRONMENT {{ ENVIRONMENT }} variable
  lineinfile:
    path: /etc/environment
    line: "ENVIRONMENT={{ ENVIRONMENT }}"

- name: Change rights /etc/environment 0644
  file:
    path: /etc/environment
    mode: 0644

- name: enable firewall
  command: ufw allow 'Nginx HTTP'

- name: apache listen on port {{ http_port }}
  template: src=load-balancer.j2 dest=/etc/nginx/conf.d/load-balancer.conf
  notify:
    - restart nginx

- name: remove for ubuntu link of default config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - restart nginx
#- name: Create folder for keys
#  file:
#    path: "{{ path_to_key }}"
#    state: directory
#    mode: 0755

#- openssl_privatekey:
#    path: "{{ path_to_key }}/{{ key_name }}"
#    size: 2048
#
#- openssl_csr:
#    path: "{{ path_to_key }}/ansible.com.csr"
#    privatekey_path: "{{ path_to_key }}/{{ key_name }}"
#
#- name: Generate a Self Signed OpenSSL certificate
#  openssl_certificate:
#    path: "{{ path_to_key }}/{{ cert_name }}"
#    privatekey_path: "{{ path_to_key }}/{{ key_name }}"
#    csr_path: "{{ path_to_key }}/ansible.com.csr"
#    provider: selfsigned
#
#- name: change rights for certificate
#  file:
#    path: "{{ path_to_cert }}/{{ cert_name }}"
#    owner: vagrant
#    group: vagrant
#    mode: 0400

#- name: change rights for key
#  file:
#    path: "{{ path_to_key }}/{{ key_name }}"
#    owner: vagrant
#    group: vagrant
#    mode: 0400
