---
- name: install pip 
  apt: name=python-pip state=latest update_cache=yes
  tags:
    - install

- name: install pyOpenSSL
  pip:
    name: pyOpenSSL

- name: Create folder for keys
  file:
    path: "{{ path_to_key }}"
    state: directory
    mode: 0755

- name: Create key
  openssl_privatekey:
    path: "{{ path_to_key }}/{{ key_name }}"
    size: 2048

- name: Create csr
  openssl_csr:
    path: "{{ path_to_key }}/ansible.com.csr"
    privatekey_path: "{{ path_to_key }}/{{ key_name }}"

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: "{{ path_to_cert }}/{{ cert_name }}"
    privatekey_path: "{{ path_to_key }}/{{ key_name }}"
    csr_path: "{{ path_to_key }}/ansible.com.csr"
    provider: selfsigned 

- name: change rights for certificate
  file:
    path: "{{ path_to_cert }}/{{ cert_name }}"
    owner: "{{ user }}"
    group: "{{ user }}" 
    mode: 0400

- name: change rights for key
  file:
    path: "{{ path_to_key }}/{{ key_name }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0400
