---
- name: install apache2
  apt: name=apache2 state=latest update_cache=yes
  tags:
    - install_apache

- name: Change rights /etc/environment 0666
  file:
    path: /etc/environment
    mode: 0666

- name: Add ENVIRONMENT {{ ENVIRONMENT }} variable
  lineinfile:
    path: /etc/environment
    line: "ENVIRONMENT={{ ENVIRONMENT }}"

- name: Change rights /etc/environment 0644
  file:
    path: /etc/environment
    mode: 0644

- name: enabled mod_rewrite
  apache2_module: name=rewrite state=present
  notify:
    - restart apache2

- name: apache2 listen on port {{ http_port }}
  template: src=ports_conf.j2 dest=/etc/apache2/ports.conf
  notify:
    - restart apache2

- name: apache2 virtualhost on port {{ http_port }}
  template: src=default_conf.j2 dest=/etc/apache2/sites-available/000-default.conf
  notify:
    - restart apache2

#- name: change start page of server
#  template: src=index.j2 dest=/var/www/html/index.html

- name: enable ssl
  shell: a2enmod ssl

- name: install php
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - php
    - libapache2-mod-php
    - php-mysql
    - php-curl
    - php-gd
    - php-mbstring
    - php-mcrypt
    - php-xml
    - php-xmlrpc
  notify:
    - restart apache2
  tags:
    - install_php

- name: copy apache2.conf
  template: src=apache2.conf.j2 dest=/etc/apache2/apache2.conf

- name: enable mod_rewrite
  shell: a2enmod rewrite
  notify:
    - restart apache2

#- shell: apache2ctl configtest
#  register: result

#- debug:
#    var: result

- name: Download wordpress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp
    group: vagrant
    owner: vagrant
    mode: 0660

- name: Extract wordpress
  unarchive:
    src: /tmp/wordpress-4.9.8.tar.gz
    dest: /tmp
    group: vagrant
    owner: vagrant
    remote_src: yes

- name: Create .htaccess
  template: 
   src: .htaccess.j2 
   dest: /tmp/wordpress/.htaccess
   group: vagrant
   owner: vagrant
   mode: 0666

#- name: Create .htaccess
#  file:
#    path: /tmp/wordpress/.htaccess
#    group: vagrant
#    owner: vagrant
#    mode: 0666
#    state: touch

#- name: Add DirectoryIndex index.php
#  shell: echo "DirectoryIndex index.php" >> /tmp/wordpress/.htaccess

- name: Create config
  shell: cp /tmp/wordpress/wp-config-sample.php /tmp/wordpress/wp-config.php

- name: Copy all to /var/www/html
  shell: cp -a /tmp/wordpress/. /var/www/html

- name: setgid 
  file:
    path: /var/www/html
    owner: vagrant
    group: vagrant
    mode: g+s
    recurse: yes

- name: Enable to write
  file:
    path: /var/www/html/wp-content
    mode: g+w

- name: Enable to write theme
  file:
    path: /var/www/html/wp-content/themes
    mode: g+w

- name: Enable to write plugin
  file:
    path: /var/www/html/wp-content/plugins
    mode: g+w

- name: wp-config.php
  template: src=wp-config.php.j2 dest=/var/www/html/wp-config.php
