---
- name: Copy my.cnf
  template: src=my_cnf.j2 dest=/etc/mysql/my.cnf
  notify:
    - restart mysql

- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: FLUSH PRIVILEGES
  command: >
    mysql --user=root --password=root {{ DB_replication }}
    --execute="FLUSH PRIVILEGES;"

- name: USE {{ DB_replication }}
  command: >
    mysql --user=root --password=root {{ DB_replication }}
    --execute="USE {{ DB_replication }};"

- name: FLUSH TABLES WITH READ LOCK
  command: >
    mysql --user=slave --password={{ mysql_slave }} {{ DB_replication }}
    --execute="FLUSH TABLES WITH READ LOCK;"

- name: SHOW MASTER STATUS
  mysql_replication:
    config_file: /etc/mysql/my.cnf
    login_user: root 
    login_password: "{{ mysql_root }}"
    mode: getmaster
  register: master

#- name: show master
#  debug: 
#    msg: "{{ master.File, master.Position }}"

- name: Dump {{ DB_replication }} to {{ DB_replication }}.sql
  mysql_db:
    state: dump
    login_user: root
    login_password: "{{ mysql_root }}"
    name: "{{ DB_replication }}"
    target: /tmp/{{ DB_replication }}.sql

- name: UNLOCK TABLES
  command: >
    mysql --user=slave --password={{ mysql_slave }} {{ DB_replication }}
    --execute="UNLOCK TABLES;"

- name: Copy {{ DB_replication }}.sql to slave
  fetch:
    src: "/tmp/{{ DB_replication }}.sql"
    dest: /tmp 
  tags:
    - copy 
